"""Trained model -> one self-contained stdlib-only .py casting."""

import argparse
import base64
import importlib.util
import json
import os
import random
import statistics
import subprocess
import sys
import time
from string import Template

import numpy as np
import torch

from featurise import FEATURE_DIM, NGRAM_SIZES, featurise_batch
from train import HIDDEN_DIM, SEED, train

DATA_DIR = "data"
ACCEPTANCE_N = 50
TIMING_N = 1000
FRESH_HASH_SEED = "12345"

CASTING = Template('''"""$task_name classifier. Generated by Foundry.

Self-contained: standard library only. No torch, no numpy.
"""

import array
import base64
import math
import sys
import zlib

FEATURE_DIM = $feature_dim
HIDDEN_DIM = $hidden_dim
NUM_CLASSES = $num_classes
NGRAM_SIZES = $ngram_sizes
LABELS = $labels


def _load(encoded):
    values = array.array("f")
    values.frombytes(base64.b64decode(encoded))
    if sys.byteorder != "little":
        values.byteswap()
    return values


def _load_int8(encoded):
    values = array.array("b")
    values.frombytes(base64.b64decode(encoded))
    return values


# W1Q is the first layer transposed to (FEATURE_DIM, HIDDEN_DIM) so that a
# sparse feature index selects one contiguous row, then symmetrically
# quantised to int8 with one scale per hidden unit. W1S holds those
# HIDDEN_DIM scales.
_W1Q = _load_int8("$w1q")
_W1S = _load("$w1s")
_B1 = _load("$b1")
_W2 = _load("$w2")
_B2 = _load("$b2")


def featurise(text):
    """Sparse (index, value) pairs. Must match foundry/featurise.py exactly."""
    cleaned = " ".join(text.lower().split())
    counts = {}
    for n in NGRAM_SIZES:
        for i in range(len(cleaned) - n + 1):
            index = zlib.crc32(cleaned[i:i + n].encode("utf-8")) % FEATURE_DIM
            counts[index] = counts.get(index, 0.0) + 1.0

    if not counts:
        raise ValueError(
            "no n-grams produced: text is shorter than %d characters after "
            "whitespace collapsing" % min(NGRAM_SIZES)
        )

    norm = math.sqrt(sum(v * v for v in counts.values()))
    if norm == 0.0:
        raise ValueError("zero-norm feature vector despite non-zero n-gram count")
    return [(index, value / norm) for index, value in counts.items()]


def logits(text):
    # Accumulate against raw int8 weights. Each scale is per hidden unit and
    # constant across features, so it applies once after the loop rather than
    # once per inner iteration. The accumulator stays float because the feature
    # value is a float; the win is one fewer multiply per inner iteration.
    unscaled = [0.0] * HIDDEN_DIM
    for index, value in featurise(text):
        offset = index * HIDDEN_DIM
        for j in range(HIDDEN_DIM):
            unscaled[j] += value * _W1Q[offset + j]

    hidden = [0.0] * HIDDEN_DIM
    for j in range(HIDDEN_DIM):
        activation = unscaled[j] * _W1S[j] + _B1[j]
        if activation > 0.0:
            hidden[j] = activation

    out = []
    for k in range(NUM_CLASSES):
        offset = k * HIDDEN_DIM
        total = _B2[k]
        for j in range(HIDDEN_DIM):
            total += _W2[offset + j] * hidden[j]
        out.append(total)
    return out


def classify(text):
    scores = logits(text)
    best = 0
    for k in range(1, NUM_CLASSES):
        if scores[k] > scores[best]:
            best = k
    return LABELS[best]


if __name__ == "__main__":
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        print(classify(line))
''')


def to_base64(tensor) -> str:
    """Little-endian float32 bytes, base64 encoded."""
    return base64.b64encode(tensor.detach().numpy().astype("<f4").tobytes()).decode("ascii")


def quantise_per_column(weight_t):
    """Symmetric int8 quantisation of (FEATURE_DIM, HIDDEN_DIM), one scale per column.

    Per-column, not per-tensor: each hidden unit gets its own scale, so a unit
    with small weights is not crushed by another unit's large ones.
    Returns (int8 base64, float32 scales base64).
    """
    weights = weight_t.detach().numpy().astype("float32")
    max_abs = np.abs(weights).max(axis=0)

    # A hidden unit with all-zero weights has no scale to derive. 1.0 is exact
    # there, since every quantised value is 0 and dequantises back to 0.
    degenerate = int((max_abs == 0).sum())
    if degenerate:
        print(f"note: {degenerate} hidden unit(s) have all-zero weights; scale set to 1.0")
    scales = np.where(max_abs == 0, 1.0, max_abs / 127.0).astype("float32")

    quantised = np.rint(weights / scales).astype("int32")
    if quantised.min() < -127 or quantised.max() > 127:
        raise ValueError(
            f"quantised values out of int8 symmetric range: "
            f"[{quantised.min()}, {quantised.max()}]"
        )
    quantised = quantised.astype("int8")

    error = np.abs(weights - quantised.astype("float32") * scales)
    print(f"quantisation: max abs error {error.max():.3e}, "
          f"mean {error.mean():.3e}, scales {scales.min():.3e}..{scales.max():.3e}")

    return (
        base64.b64encode(quantised.tobytes()).decode("ascii"),
        base64.b64encode(scales.astype("<f4").tobytes()).decode("ascii"),
    )


def emit(model, spec, path):
    state = model.state_dict()
    weight1, bias1 = state["0.weight"], state["0.bias"]
    weight2, bias2 = state["2.weight"], state["2.bias"]

    expected1 = (HIDDEN_DIM, FEATURE_DIM)
    if tuple(weight1.shape) != expected1:
        raise ValueError(f"layer 0 weight is {tuple(weight1.shape)}, expected {expected1}")
    if tuple(weight2.shape) != (spec["num_classes"], HIDDEN_DIM):
        raise ValueError(f"layer 2 weight is {tuple(weight2.shape)}, unexpected")

    w1q, w1s = quantise_per_column(weight1.t().contiguous())
    source = CASTING.substitute(
        task_name=spec["task_name"],
        feature_dim=FEATURE_DIM,
        hidden_dim=HIDDEN_DIM,
        num_classes=spec["num_classes"],
        ngram_sizes=repr(tuple(NGRAM_SIZES)),
        labels=json.dumps([label["name"] for label in spec["labels"]]),
        w1q=w1q,
        w1s=w1s,
        b1=to_base64(bias1),
        w2=to_base64(weight2),
        b2=to_base64(bias2),
    )

    with open(path, "w") as f:
        f.write(source)
    return path


def load_json(task_dir, name):
    path = os.path.join(task_dir, name)
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found. Generate the corpus first.")
    with open(path) as f:
        return json.load(f)


def casting_path(task_dir, spec):
    return os.path.join(task_dir, f"{spec['task_name']}_classifier.py")


def main(task_dir):
    spec = load_json(task_dir, "spec.json")
    train_examples = load_json(task_dir, "train_A.json")
    test_examples = load_json(task_dir, "test_B.json")
    labels = [label["name"] for label in spec["labels"]]

    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)

    X_train = featurise_batch([ex["text"] for ex in train_examples])
    y_train = np.array([ex["label"] for ex in train_examples], dtype=np.int64)
    X_test = featurise_batch([ex["text"] for ex in test_examples])
    y_test = np.array([ex["label"] for ex in test_examples], dtype=np.int64)

    print(f"training on {len(train_examples)} examples, {spec['num_classes']} classes")
    model, metrics = train(X_train, y_train, X_test, y_test, spec["num_classes"])
    print(f"torch test accuracy: {metrics['test_accuracy']:.4f}")
    print()

    path = casting_path(task_dir, spec)
    emit(model, spec, path)
    size_kb = os.path.getsize(path) / 1024
    print(f"emitted: {path}")
    print(f"size: {size_kb:.1f} KB")

    source = open(path).read()
    for banned in ("import torch", "import numpy"):
        if banned in source:
            raise ValueError(f"emitted casting contains {banned!r}")
    print("emitted file contains no torch/numpy import")
    print()

    # --- acceptance: fresh subprocess, different PYTHONHASHSEED -------------
    sample = test_examples[:ACCEPTANCE_N]
    # Newlines are collapsed to single spaces by the featuriser anyway, so
    # flattening them for line-oriented stdin does not change the features.
    stdin_text = "\n".join(" ".join(ex["text"].split()) for ex in sample) + "\n"

    model.eval()
    with torch.no_grad():
        torch_indices = model(torch.from_numpy(X_test[:ACCEPTANCE_N])).argmax(dim=1).tolist()
    torch_labels = [labels[i] for i in torch_indices]

    env = dict(os.environ)
    env["PYTHONHASHSEED"] = FRESH_HASH_SEED
    completed = subprocess.run(
        [sys.executable, path],
        input=stdin_text,
        capture_output=True,
        text=True,
        env=env,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"casting subprocess exited {completed.returncode}\n{completed.stderr}"
        )

    emitted_labels = completed.stdout.strip().split("\n")
    print(f"subprocess: {sys.executable} with PYTHONHASHSEED={FRESH_HASH_SEED}")
    print(f"torch predictions: {len(torch_labels)}   casting predictions: {len(emitted_labels)}")
    if len(emitted_labels) != len(torch_labels):
        raise ValueError("casting returned a different number of predictions")

    mismatches = [
        (i, torch_labels[i], emitted_labels[i], sample[i]["text"])
        for i in range(len(torch_labels))
        if torch_labels[i] != emitted_labels[i]
    ]
    for i, expected, got, text in mismatches:
        print(f"MISMATCH {i}: torch={expected} casting={got} text={text[:80]!r}")

    print(f"mismatches: {len(mismatches)} of {len(torch_labels)}")
    print()

    # --- timing ------------------------------------------------------------
    module_spec = importlib.util.spec_from_file_location("casting", path)
    casting = importlib.util.module_from_spec(module_spec)
    module_spec.loader.exec_module(casting)

    texts = [ex["text"] for ex in test_examples]
    timings = []
    for i in range(TIMING_N):
        text = texts[i % len(texts)]
        start = time.perf_counter()
        casting.classify(text)
        timings.append((time.perf_counter() - start) * 1000.0)

    print(f"timed {TIMING_N} classifications")
    print(f"median latency: {statistics.median(timings):.3f} ms")
    print(f"mean latency:   {statistics.mean(timings):.3f} ms")
    print(f"min / max:      {min(timings):.3f} / {max(timings):.3f} ms")
    print()

    print(f"ACCEPTANCE exact match on {ACCEPTANCE_N} examples: "
          f"{len(mismatches) == 0} ({len(torch_labels) - len(mismatches)}/{len(torch_labels)})")
    print("ACCEPTANCE CHECK:", "PASS" if not mismatches else "FAIL")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Emit and verify a task's casting.")
    parser.add_argument("task_dir", help="directory holding spec.json, train_A.json, test_B.json")
    main(parser.parse_args().task_dir)
