"""Plain English need -> task spec JSON."""

import json

import anthropic

PRIMARY_MODEL = "claude-sonnet-5"
FALLBACK_MODEL = "claude-opus-5"

SYSTEM_PROMPT = """You design specifications for text classification tasks.

Return ONLY raw JSON. No markdown fences, no preamble, no commentary, no
trailing explanation. Your entire response must parse with json.loads().

Schema:
{
  "task_name": "<short snake_case name>",
  "num_classes": <integer, equal to the length of "labels">,
  "labels": [
    {
      "name": "<short snake_case label name>",
      "definition": "<one or two sentences stating precisely what belongs in this class>",
      "examples_of_edge_cases": ["<a hard or ambiguous case>", "..."]
    }
  ],
  "generation_personas": [
    "<a distinct writer profile: who they are, their situation, how they write>"
  ]
}

Requirements:
- Between 3 and 6 labels. They must be mutually exclusive and jointly cover
  the need. Include a catch-all class if the need implies one.
- Each label needs at least 2 examples_of_edge_cases, written as realistic
  message text, not descriptions.
- At least 8 generation_personas, genuinely distinct from each other in who
  the writer is, what situation they are in, their literacy level, and their
  device and language habits. These drive corpus diversity, so avoid writing
  eight variations of the same person."""


def strip_fences(raw: str) -> str:
    """Remove ```json / ``` wrappers if the model added them despite instructions."""
    text = raw.strip()
    if not text.startswith("```"):
        return text
    lines = text.split("\n")
    lines = lines[1:]  # drop the opening ``` or ```json
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    return "\n".join(lines).strip()


def parse_json(raw: str):
    """Strip fences, then parse. Genuinely malformed JSON raises JSONDecodeError."""
    return json.loads(strip_fences(raw))


def validate_spec(spec: dict) -> None:
    """Crash loudly if the spec is unusable downstream."""
    for key in ("task_name", "labels", "generation_personas", "num_classes"):
        if key not in spec:
            raise ValueError(f"spec missing required key {key!r}; got keys {sorted(spec)}")

    if not isinstance(spec["labels"], list) or not spec["labels"]:
        raise ValueError("spec['labels'] must be a non-empty list")

    for i, label in enumerate(spec["labels"]):
        for key in ("name", "definition", "examples_of_edge_cases"):
            if key not in label:
                raise ValueError(f"labels[{i}] missing required key {key!r}: {label}")

    names = [label["name"] for label in spec["labels"]]
    if len(set(names)) != len(names):
        raise ValueError(f"duplicate label names: {names}")

    if spec["num_classes"] != len(spec["labels"]):
        raise ValueError(
            f"num_classes={spec['num_classes']} but got {len(spec['labels'])} labels"
        )

    if len(spec["generation_personas"]) < 8:
        raise ValueError(
            f"need at least 8 generation_personas, got {len(spec['generation_personas'])}"
        )


def make_spec(need: str) -> dict:
    """Turn a plain English need into a validated task spec."""
    client = anthropic.Anthropic()
    prompt = f"Design a text classification task for this need:\n\n{need}"

    model = PRIMARY_MODEL
    try:
        response = client.messages.create(
            model=model,
            max_tokens=16000,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )
    except anthropic.NotFoundError as exc:
        # Narrow, deliberate fallback: only when the model string itself is
        # rejected. Every other failure propagates.
        print(f"model {PRIMARY_MODEL!r} rejected ({exc.__class__.__name__}), "
              f"falling back to {FALLBACK_MODEL!r}")
        model = FALLBACK_MODEL
        response = client.messages.create(
            model=model,
            max_tokens=16000,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

    print(f"spec generated by: {model}")
    print(f"stop_reason: {response.stop_reason}")

    text = "".join(block.text for block in response.content if block.type == "text")
    spec = parse_json(text)
    validate_spec(spec)
    return spec
